from __future__ import annotations

"""Shared activation-proxy cache helpers for DeepX Stage2 experiments.

The heavy lifting is intentionally shared with the Hailo Part2 path: run the
split Part1 ONNX with ONNX Runtime and collect the tensors that feed Part2.
For broad screening this can use ORT CPU, ORT CUDA, or ORT TensorRT depending on
``ONNX_SPLITPOINT_ACTIVATION_PROXY_BACKEND``.  The cache is still labelled as a
proxy unless generated by the exact runtime producer.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional


def _safe_rel(path: Path, base: Path) -> str:
    try:
        return os.path.relpath(path, base).replace("\\", "/")
    except Exception:
        return str(path).replace("\\", "/")


def generate_deepx_stage2_activation_proxy_cache(
    *,
    case_dir: str | Path,
    part1_onnx: str | Path,
    part2_onnx: str | Path,
    calibration_dir: str | Path,
    sample_count: int = 100,
    batch_size: int = 1,
    store_samples: Optional[int] = None,
    stage2_backend: str = "deepx_m1",
) -> Dict[str, Any]:
    """Generate a case-level ActivationCalibrationCache for DeepX Stage2.

    Returns a JSON-safe status dict.  ``manifest_rel`` is suitable for storing in
    ``split_manifest.json``.  The manifest uses the same schema as Hailo's proxy
    cache, so benchmark-suite gates and reporting can reuse it.
    """
    case = Path(case_dir).expanduser().resolve()
    part1 = Path(part1_onnx).expanduser().resolve()
    part2 = Path(part2_onnx).expanduser().resolve()
    calib = Path(calibration_dir).expanduser().resolve()
    out_dir = case / "deepx" / "deepx_m1" / "part2" / "activation_proxy"
    out_dir.mkdir(parents=True, exist_ok=True)
    try:
        from ..hailo_backend import _build_activation_calib_from_part1_onnx, _write_activation_proxy_cache_manifest
    except Exception as exc:
        return {"ok": False, "status": "helper_import_failed", "error": f"{type(exc).__name__}: {exc}"}
    try:
        # DeepX part2 compilation may need actual .npz samples.  Store all proxy
        # samples by default, but cap to sample_count.  Hailo's default remains
        # manifest-only unless explicitly requested.
        n_store = int(sample_count if store_samples is None else store_samples)
        names, arrays, debug = _build_activation_calib_from_part1_onnx(
            part1_onnx=part1,
            part2_onnx=part2,
            calib_dir=calib,
            limit=max(1, int(sample_count)),
            gen_batch=max(1, int(batch_size)),
        )
        manifest_path_s = _write_activation_proxy_cache_manifest(
            out_dir=out_dir,
            part1_onnx=part1,
            part2_onnx=part2,
            calib_dir=calib,
            calib_arrays_by_part2_input=arrays,
            activation_debug=debug,
            eff_count=max(1, int(sample_count)),
            gen_batch=max(1, int(batch_size)),
            stage2_backend=str(stage2_backend),
            force_store_samples=max(0, int(n_store)),
        )
        if not manifest_path_s:
            return {"ok": False, "status": "manifest_write_failed"}
        src = Path(manifest_path_s)
        dst_dir = case / "activation_calibration"
        dst_dir.mkdir(parents=True, exist_ok=True)
        dst = dst_dir / "manifest.json"
        payload = json.loads(src.read_text(encoding="utf-8"))
        payload.update({
            "created_by": "onnx_splitpoint_tool_v52v",
            "stage2_backend": str(stage2_backend),
            "stage2_target": "deepx_m1",
            "case_id": case.name,
            "part1_onnx": _safe_rel(part1, case),
            "part2_onnx": _safe_rel(part2, case),
            "compiler_consumed_direct": False,
            "compiler_consumed_direct_reason": "DeepX part2 DX-COM tensor-loader build is experimental; manifest/samples are prepared for the build step.",
        })
        dst.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        # Copy optional sample files next to the case-level manifest so future
        # DeepX/Hailo part2 builds can consume the same data without knowing the
        # backend-specific staging dir.
        for sample in sorted(src.parent.glob("sample_*.npz")):
            try:
                import shutil
                shutil.copy2(sample, dst_dir / sample.name)
            except Exception:
                pass
        try:
            import shutil
            st = src.parent / "stats.json"
            if st.is_file():
                shutil.copy2(st, dst_dir / "stats.json")
        except Exception:
            pass
        return {
            "ok": True,
            "status": "ready",
            "manifest": str(dst),
            "manifest_rel": _safe_rel(dst, case),
            "source_manifest": str(src),
            "sample_count": payload.get("sample_count"),
            "stored_sample_count": payload.get("stored_sample_count"),
            "source": payload.get("source"),
            "producer_backend": payload.get("producer_backend"),
            "requested_backend": payload.get("requested_backend"),
            "provider_fallback_reason": payload.get("provider_fallback_reason"),
            "trust_level": payload.get("trust_level"),
            "producer_exact": payload.get("producer_exact"),
            "tensor_count": len(payload.get("tensors") or []),
            "debug": {"part2_inputs": list(names)},
        }
    except Exception as exc:
        return {"ok": False, "status": "failed", "error": f"{type(exc).__name__}: {exc}"}


def _onnx_input_shapes_for_tensor_config(onnx_path: str | Path, manifest_path: str | Path | None = None) -> dict[str, list[int]]:
    """Return static-ish input shapes for a split Part2 ONNX.

    Dynamic dimensions are filled from activation proxy manifest sample shapes when
    possible.  DX-COM still may reject dynamic/unsupported tensor loaders; this
    helper is only for the experimental Part2 build wrapper.
    """
    shapes: dict[str, list[int]] = {}
    manifest_tensors: dict[str, list[int]] = {}
    if manifest_path:
        try:
            obj = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
            for t in list(obj.get("tensors") or []):
                if not isinstance(t, dict):
                    continue
                name = str(t.get("name") or "").strip()
                sample = t.get("sample_shape") or t.get("shape") or []
                if name and isinstance(sample, list):
                    dims = []
                    for x in sample:
                        try:
                            dims.append(int(x))
                        except Exception:
                            pass
                    if dims:
                        manifest_tensors[name] = dims
        except Exception:
            pass
    try:
        import onnx  # type: ignore
        model = onnx.load(str(onnx_path))
        for inp in model.graph.input:
            name = str(inp.name)
            dims: list[int] = []
            for d in inp.type.tensor_type.shape.dim:
                val = int(d.dim_value) if getattr(d, "dim_value", 0) else 0
                dims.append(val)
            if any(v <= 0 for v in dims):
                sample = manifest_tensors.get(name)
                if sample:
                    # manifest sample shape usually excludes batch; prepend batch if needed
                    if len(sample) == len(dims) - 1:
                        sample_full = [1] + sample
                    else:
                        sample_full = sample
                    dims = [int(sample_full[i]) if i < len(sample_full) and int(sample_full[i]) > 0 else (1 if i == 0 else 1) for i in range(len(dims))]
                else:
                    dims = [1 if i == 0 else (int(v) if int(v) > 0 else 1) for i, v in enumerate(dims)]
            shapes[name] = [int(x) for x in dims]
    except Exception:
        # Fall back to manifest tensors only.
        for name, sample in manifest_tensors.items():
            shapes[name] = [1] + [int(x) for x in sample]
    return shapes





def _read_text_tail(path: str | Path | None, limit: int = 8000) -> str:
    if not path:
        return ""
    try:
        p = Path(path)
        if not p.is_file():
            return ""
        data = p.read_text(encoding="utf-8", errors="replace")
        return data[-int(limit):]
    except Exception:
        return ""


def _classify_dxcom_stage2_failure(*, status: str, message: str, log_path: str | Path | None) -> Dict[str, Any]:
    """Classify known DeepX Stage2 tensor-calibration failures.

    DX-COM's default_loader is image-oriented in the versions we have tested.
    Passing .npz/.npy activation proxy samples through default_loader can make
    cv2.imread return None inside dx_com.dataloader.default_dataset, followed by
    a None.astype crash.  That is not a model compile failure in the normal
    sense; it means the feature-tensor loader adapter is not implemented for the
    installed DX-COM release.
    """
    blob = "\n".join([str(status or ""), str(message or ""), _read_text_tail(log_path)]).lower()
    if (
        "default_dataset.py" in blob
        and "nonetype" in blob
        and "astype" in blob
    ) or (
        "none" in blob and "astype" in blob and ("npz" in blob or "npy" in blob or "cv2" in blob)
    ):
        return {
            "status": "unsupported_dxcom_tensor_loader",
            "error_class": "dxcom_default_loader_cannot_read_activation_npz",
            "summary": "DX-COM default_loader rejected NPZ/NPY activation-proxy samples; a custom DeepX feature-tensor calibration loader is required for Part2 DXNN builds.",
            "next_action": "implement_custom_dxcom_tensor_activation_loader_or_use_deepx_part1_to_tensorrt_only",
            "counts_as_split_benchmark": False,
            "can_run_stage2": False,
            "severity": "expected_experimental_unsupported",
        }
    return {}

def _onnx_io_contract(path: Path) -> Dict[str, Any]:
    try:
        import onnx  # type: ignore
        m = onnx.load(str(path))
        def dims(v):
            out = []
            for d in v.type.tensor_type.shape.dim:
                if getattr(d, 'dim_value', 0):
                    out.append(int(d.dim_value))
                elif getattr(d, 'dim_param', ''):
                    out.append(str(d.dim_param))
                else:
                    out.append(None)
            return out
        return {
            'inputs': [{'name': i.name, 'shape': dims(i)} for i in m.graph.input],
            'outputs': [{'name': o.name, 'shape': dims(o)} for o in m.graph.output],
        }
    except Exception as exc:
        return {'inputs': [], 'outputs': [], 'error': f'{type(exc).__name__}: {exc}'}



def _activation_manifest_contract_check(inputs: dict[str, list[int]], manifest_path: Path) -> Dict[str, Any]:
    out: Dict[str, Any] = {
        "schema_version": 1,
        "status": "unknown",
        "part2_inputs": {str(k): [int(x) for x in v] for k, v in (inputs or {}).items()},
        "activation_tensors": {},
        "matches": {},
        "missing_inputs": [],
        "extra_tensors": [],
        "ambiguous_same_shape_groups": [],
    }
    try:
        obj = json.loads(Path(manifest_path).read_text(encoding="utf-8"))
        tensors = {}
        for t in list(obj.get("tensors") or []):
            if not isinstance(t, dict):
                continue
            name = str(t.get("name") or "").strip()
            shp = t.get("sample_shape") or t.get("shape") or []
            if name and isinstance(shp, list):
                tensors[name] = [int(x) for x in shp if str(x).lstrip('-').isdigit()]
        out["activation_tensors"] = tensors
        missing = []
        matches = {}
        for name, in_shape in (inputs or {}).items():
            base = list(in_shape[1:]) if len(in_shape) > 1 and int(in_shape[0]) == 1 else list(in_shape)
            tshp = tensors.get(str(name))
            ok = bool(tshp == base or tshp == list(in_shape))
            matches[str(name)] = {"input_shape": list(in_shape), "expected_sample_shape": base, "activation_shape": tshp, "shape_match": ok}
            if not ok:
                missing.append(str(name))
        extras = [k for k in tensors.keys() if k not in set(inputs.keys())]
        # Find same-shape ambiguity; this is exactly where input order/layout has to be checked at runtime.
        by_shape: Dict[str, list[str]] = {}
        for name, shp in tensors.items():
            by_shape.setdefault("x".join(str(x) for x in shp), []).append(name)
        amb = [{"shape": k, "tensors": v} for k, v in by_shape.items() if len(v) > 1]
        out.update({"matches": matches, "missing_inputs": missing, "extra_tensors": extras, "ambiguous_same_shape_groups": amb})
        out["status"] = "ok" if not missing else "shape_or_name_mismatch"
    except Exception as exc:
        out.update({"status": "error", "error": f"{type(exc).__name__}: {exc}"})
    return out

def compile_deepx_stage2_from_activation_proxy(
    *,
    case_dir: str | Path,
    part2_onnx: str | Path,
    activation_manifest: str | Path,
    compiler_root: str | Path | None = None,
    compiler_venv: str | Path | None = None,
    calibration_num: int = 100,
    opt_level: int = 0,
    timeout_s: int = 7200,
) -> Dict[str, Any]:
    """Experimental ONNX Part2 -> DXNN build from activation proxy NPZ samples.

    This intentionally remains best-effort.  DX-COM feature-tensor loader support
    may vary by release.  Failures are returned as structured status and should
    not abort benchmarkset generation.
    """
    case = Path(case_dir).expanduser().resolve()
    p2 = Path(part2_onnx).expanduser().resolve()
    manifest = Path(activation_manifest).expanduser().resolve()
    out_dir = case / "deepx" / "deepx_m1" / "part2"
    act_dir = manifest.parent
    try:
        inputs = _onnx_input_shapes_for_tensor_config(p2, manifest)
        if not inputs:
            raise RuntimeError("could not determine Part2 ONNX input shapes for DeepX tensor activation config")
        contract_check = _activation_manifest_contract_check(inputs, manifest)
        from .config import tensor_activation_dxcom_config, write_dxcom_config
        from .compiler import compile_dxnn, compile_dxnn_with_npz_cv2_shim, compile_dxnn_with_tensor_loader
        cfg = tensor_activation_dxcom_config(
            inputs=inputs,
            calibration_dir=act_dir,
            calibration_num=int(calibration_num),
            calibration_method="ema",
        )
        cfg_path = write_dxcom_config(cfg, out_dir / "config_deepx_tensor_activation.json")

        requested_loader_mode = str(os.environ.get('ONNX_SPLITPOINT_DEEPX_STAGE2_LOADER') or 'custom_tensor').strip().lower()
        used_npz_shim = False
        used_tensor_loader = False
        loader_attempts: list[dict[str, Any]] = []

        def _attempt_loader(mode: str):
            nonlocal used_npz_shim, used_tensor_loader
            mode = str(mode or 'custom_tensor').strip().lower()
            if mode in {'default', 'dxcom_default'}:
                _res = compile_dxnn(
                    onnx_path=p2,
                    config_path=cfg_path,
                    output_dir=out_dir,
                    compiler_root=compiler_root,
                    compiler_venv=compiler_venv,
                    opt_level=int(opt_level),
                    timeout_s=int(timeout_s),
                )
                return _res, {'mode': mode, 'adapter': 'dxcom_default_loader'}
            if mode in {'cv2_shim', 'npz_cv2_shim'}:
                if len(inputs) != 1:
                    raise RuntimeError('npz_cv2_shim supports only single-input Stage2 ONNX models')
                _input_name, _input_shape = next(iter(inputs.items()))
                _res = compile_dxnn_with_npz_cv2_shim(
                    onnx_path=p2,
                    config_path=cfg_path,
                    output_dir=out_dir,
                    input_name=str(_input_name),
                    input_shape=list(_input_shape),
                    compiler_root=compiler_root,
                    compiler_venv=compiler_venv,
                    opt_level=int(opt_level),
                    timeout_s=int(timeout_s),
                )
                used_npz_shim = True
                return _res, {'mode': mode, 'adapter': 'cv2_imread_npz_shim_single_input'}
            _res = compile_dxnn_with_tensor_loader(
                onnx_path=p2,
                config_path=cfg_path,
                output_dir=out_dir,
                activation_manifest=manifest,
                compiler_root=compiler_root,
                compiler_venv=compiler_venv,
                opt_level=int(opt_level),
                timeout_s=int(timeout_s),
            )
            used_tensor_loader = True
            return _res, {'mode': mode, 'adapter': 'custom_dxcom_tensor_activation_loader'}

        # v54: try a real custom tensor activation loader first, then fall back
        # to the pragmatic NPZ->cv2.imread shim for the common single-input
        # Stage2 case.  DX-COM releases differ in how deeply the default_loader
        # can be patched, so cascading here avoids losing a long benchmark build
        # just because one adapter flavor is unsupported.
        loader_modes: list[str] = []
        if requested_loader_mode:
            loader_modes.append(requested_loader_mode)
        for _m in ('custom_tensor', 'npz_cv2_shim', 'dxcom_default'):
            if _m not in loader_modes:
                loader_modes.append(_m)
        res = None
        selected_loader_info: dict[str, Any] = {}
        for _mode in loader_modes:
            try:
                _res, _info = _attempt_loader(_mode)
                loader_attempts.append({
                    **_info,
                    'ok': bool(_res.ok),
                    'status': str(_res.status or ''),
                    'returncode': _res.returncode,
                    'log_path': str(_res.log_path or ''),
                    'message_tail': str(_res.message or '')[-500:],
                })
                if _res.ok:
                    res = _res
                    selected_loader_info = dict(_info)
                    break
                if res is None:
                    res = _res
                    selected_loader_info = dict(_info)
            except Exception as _loader_exc:
                loader_attempts.append({'mode': str(_mode), 'ok': False, 'status': 'exception', 'error': f'{type(_loader_exc).__name__}: {_loader_exc}'})
        if res is None:
            raise RuntimeError('all DeepX Stage2 tensor loader attempts failed before invoking DX-COM')
        canonical_dxnn = out_dir / "model.dxnn"
        dxnn_src = Path(res.dxnn_path).expanduser() if res.dxnn_path else None
        if bool(res.ok) and dxnn_src is not None and dxnn_src.exists() and dxnn_src.resolve() != canonical_dxnn.resolve():
            try:
                canonical_dxnn.write_bytes(dxnn_src.read_bytes())
            except Exception:
                canonical_dxnn = dxnn_src
        elif dxnn_src is not None and dxnn_src.exists():
            canonical_dxnn = dxnn_src
        io_contract = {
            "schema_version": 1,
            "backend": "deepx_m1",
            "variant": "part2",
            "stage": "part2",
            "artifact_kind": "dxnn",
            "experimental": True,
            "calibration_source": "activation_proxy",
            "activation_manifest": str(manifest),
            "activation_dir": str(act_dir),
            "onnx": _onnx_io_contract(p2),
            "inputs": inputs,
            "stage2_contract_check": contract_check,
            "dxnn_path": str(canonical_dxnn if bool(res.ok) else (res.dxnn_path or "")),
        }
        try:
            (out_dir / "output_contract.json").write_text(json.dumps(io_contract, indent=2, ensure_ascii=False), encoding="utf-8")
        except Exception:
            pass
        status = {
            "ok": bool(res.ok),
            "status": "ready" if res.ok else str(res.status or "failed"),
            "experimental": True,
            "stage": "part2",
            "backend": "deepx_m1",
            "artifact_kind": "dxnn",
            "dxnn_path": str(canonical_dxnn if bool(res.ok) else (res.dxnn_path or "")),
            "canonical_dxnn_path": str(out_dir / "model.dxnn"),
            "config_path": str(cfg_path),
            "contract_path": str(out_dir / "output_contract.json"),
            "build_log": str(res.log_path or ""),
            "activation_manifest": str(manifest),
            "activation_dir": str(act_dir),
            "inputs": inputs,
            "stage2_contract_check": contract_check,
            "message": str(res.message or ""),
            "returncode": res.returncode,
            "used_npz_cv2_shim": bool(locals().get("used_npz_shim", False)),
            "used_tensor_loader": bool(locals().get("used_tensor_loader", False)),
            "npz_cv2_shim_loader": bool(locals().get("used_npz_shim", False)),
            "tensor_loader_adapter": str((locals().get("selected_loader_info") or {}).get("adapter") or ("cv2_imread_npz_shim_single_input" if bool(locals().get("used_npz_shim", False)) else "custom_dxcom_tensor_activation_loader")),
            "tensor_loader_selected_mode": str((locals().get("selected_loader_info") or {}).get("mode") or ""),
            "tensor_loader_attempts": list(locals().get("loader_attempts") or []),
        }
        if not bool(res.ok):
            classified = _classify_dxcom_stage2_failure(status=str(res.status or ""), message=str(res.message or ""), log_path=res.log_path)
            if classified:
                # Preserve the raw compiler status while replacing the public
                # status with an actionable, non-misleading error class.
                status["raw_status"] = status.get("status")
                status.update(classified)
        try:
            (out_dir / "stage2_build_status.json").write_text(json.dumps(status, indent=2, ensure_ascii=False), encoding="utf-8")
        except Exception:
            pass
        return status
    except Exception as exc:
        status = {
            "ok": False,
            "status": "failed",
            "experimental": True,
            "stage": "part2",
            "backend": "deepx_m1",
            "artifact_kind": "dxnn",
            "activation_manifest": str(manifest),
            "error": f"{type(exc).__name__}: {exc}",
        }
        try:
            out_dir.mkdir(parents=True, exist_ok=True)
            (out_dir / "stage2_build_status.json").write_text(json.dumps(status, indent=2, ensure_ascii=False), encoding="utf-8")
        except Exception:
            pass
        return status
