"""Paired, hardware-free DeepX classification preprocessing probe.

The probe deliberately runs the *same* float ONNX model and the *same* ordered
validation samples twice.  Only the numeric transform after canonical RGB
resize differs:

``current_scale_only``
    ``RGB uint8 -> float32 / 255`` (the historical DX-COM recipe).

``imagenet_mean_std``
    ``RGB uint8 -> float32 / 255 -> (x - mean) / std``.

This does not emulate DeepX quantization.  It is an inexpensive paired control
that separates a preprocessing-domain mismatch from compiler/quantization
effects before two costly DXNN artifacts are built.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

import numpy as np

from ..preprocessing_contract import (
    canonical_image_preprocessing_contract,
    prepare_rgb_uint8_image,
    preprocessing_contract_sha256,
)
from .config import (
    CLASSIFICATION_PREPROCESSING_CURRENT,
    CLASSIFICATION_PREPROCESSING_IMAGENET,
    IMAGENET_RGB_MEAN,
    IMAGENET_RGB_STD,
    canonical_classification_preprocessing,
    deepx_classification_preprocessing_contract,
)


PROBE_SCHEMA = "onnx-splitpoint/deepx-classification-preprocessing-probe"
PROBE_SCHEMA_VERSION = 1


def sha256_file(path: str | Path, *, chunk_size: int = 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(chunk_size), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_json_sha256(value: Any) -> str:
    encoded = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


@dataclass(frozen=True)
class ProbeSample:
    image_id: str
    path: Path
    label_id: int
    declared_sha256: str = ""


def _resolve_manifest_ref(value: Any, *, manifest_path: Path) -> Path:
    path = Path(str(value or "")).expanduser()
    if not path.is_absolute():
        path = manifest_path.parent / path
    return path.resolve()


def _read_synset_map(path: Path | None) -> dict[str, int]:
    if path is None or not path.is_file():
        return {}
    mapping: dict[str, int] = {}
    for index, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines()):
        text = line.strip()
        if not text:
            continue
        wnid = text.split(None, 1)[0]
        if wnid.startswith("n") and wnid[1:].isdigit():
            mapping[wnid] = index
    return mapping


def load_probe_samples(
    manifest_path: str | Path,
    *,
    expected_count: int = 0,
    verify_content: bool = False,
    limit: int = 0,
    expected_image_ids: Sequence[str] | None = None,
) -> tuple[list[ProbeSample], dict[str, Any]]:
    """Load an already selected manifest without silently re-selecting rows.

    The safest input is the suite-local ``manifest.json`` generated by the
    workflow.  It contains the exact ordered 500-image subset used by both the
    DeepX and TensorRT quality endpoints.  Dataset-registry manifests with an
    ``items`` list are also accepted, but the caller must provide an already
    selected one when exact workflow parity is required.
    """

    manifest = Path(manifest_path).expanduser().resolve()
    if not manifest.is_file():
        raise FileNotFoundError(f"validation manifest not found: {manifest}")
    payload = json.loads(manifest.read_text(encoding="utf-8"))
    if not isinstance(payload, Mapping):
        raise ValueError("validation manifest must contain one JSON object")

    labels_meta = payload.get("labels") if isinstance(payload.get("labels"), Mapping) else {}
    labels_path = None
    if labels_meta and labels_meta.get("path"):
        labels_path = _resolve_manifest_ref(labels_meta.get("path"), manifest_path=manifest)
    wnid_to_id = _read_synset_map(labels_path)

    raw_samples: list[Mapping[str, Any]]
    root: Path
    if isinstance(payload.get("samples"), list):
        raw_samples = payload["samples"]
        root = manifest.parent
    elif isinstance(payload.get("items"), list):
        raw_samples = payload["items"]
        root = _resolve_manifest_ref(payload.get("root"), manifest_path=manifest)
    else:
        raise ValueError("validation manifest has neither samples[] nor items[]")

    samples: list[ProbeSample] = []
    seen_ids: set[str] = set()
    for index, row in enumerate(raw_samples):
        if not isinstance(row, Mapping):
            raise ValueError(f"validation sample {index} is not an object")
        relative = str(
            row.get("image")
            or row.get("relative_path")
            or row.get("path")
            or ""
        ).strip()
        if not relative:
            raise ValueError(f"validation sample {index} has no image path")
        image_path = Path(relative).expanduser()
        if not image_path.is_absolute():
            image_path = root / image_path
        image_path = image_path.resolve()
        image_id = str(
            row.get("sample_id")
            or row.get("source_image")
            or row.get("relative_path")
            or row.get("image")
            or image_path.name
        ).strip()
        if not image_id or image_id in seen_ids:
            raise ValueError(f"validation sample identity is empty or duplicated: {image_id!r}")
        seen_ids.add(image_id)

        label = row.get("label_id")
        if label is None:
            class_name = str(row.get("class_name") or image_path.parent.name or "").strip()
            label = wnid_to_id.get(class_name)
        if label is None:
            raise ValueError(f"validation sample lacks a resolvable label_id: {image_id}")
        if isinstance(label, bool) or not isinstance(label, (int, np.integer)):
            raise ValueError(f"validation label_id is not an integer: {image_id}")
        try:
            label_id = int(label)
        except Exception as exc:
            raise ValueError(f"validation label_id is not an integer: {image_id}") from exc
        if label_id < 0:
            raise ValueError(f"validation label_id is negative: {image_id}")

        declared_sha = str(row.get("source_sha256") or row.get("sha256") or "").strip().lower()
        if declared_sha.startswith("sha256:"):
            declared_sha = declared_sha.split(":", 1)[1]
        if not image_path.is_file():
            raise FileNotFoundError(f"validation image missing: {image_path}")
        if verify_content and declared_sha:
            actual_sha = sha256_file(image_path)
            if actual_sha != declared_sha:
                raise ValueError(f"validation image SHA-256 mismatch: {image_id}")
        samples.append(ProbeSample(image_id, image_path, label_id, declared_sha))

    if expected_count > 0 and len(samples) != int(expected_count):
        raise ValueError(
            f"validation sample count mismatch: expected {int(expected_count)}, got {len(samples)}"
        )
    if not samples:
        raise ValueError("validation sample selection is empty")
    if expected_image_ids is not None and list(expected_image_ids) != [s.image_id for s in samples]:
        raise ValueError("ordered sample identity mismatch")
    source_count = len(samples)
    if isinstance(limit, bool) or int(limit) != limit or int(limit) < 0:
        raise ValueError("selection limit must be a nonnegative integer")
    if limit:
        if limit > source_count:
            raise ValueError("selection limit exceeds manifest sample count")
        samples = samples[:int(limit)]
    selection_rows = [
        {
            "image_id": sample.image_id,
            "label_id": sample.label_id,
            "declared_sha256": sample.declared_sha256,
        }
        for sample in samples
    ]
    identity = {
        "manifest_path": str(manifest),
        "manifest_sha256": sha256_file(manifest),
        "sample_count": len(samples),
        "source_sample_count": source_count,
        "selection_rule": "first_N_in_manifest_order" if limit else "entire_ordered_manifest",
        "selected_image_ids": [s.image_id for s in samples],
        "ordered_sample_identity_sha256": canonical_json_sha256(selection_rows),
        "labels_path": str(labels_path or ""),
        "labels_sha256": sha256_file(labels_path) if labels_path and labels_path.is_file() else "",
        "content_verified": bool(verify_content),
    }
    return samples, identity


def resolve_image_input_contract(input_shape: Sequence[Any]) -> tuple[str, tuple[int, int]]:
    dims = [int(value) if value not in (None, "") else 0 for value in input_shape]
    if len(dims) != 4 or dims[0] not in {0, 1}:
        raise ValueError(f"classification probe requires a rank-4 batch-1 input, got {dims}")
    if dims[1] == 3 and dims[2] > 0 and dims[3] > 0:
        return "NCHW", (dims[2], dims[3])
    if dims[3] == 3 and dims[1] > 0 and dims[2] > 0:
        return "NHWC", (dims[1], dims[2])
    raise ValueError(f"classification probe requires a static 3-channel image input, got {dims}")


def classification_input_tensor(
    rgb_uint8: np.ndarray,
    *,
    mode: str,
    layout: str,
) -> np.ndarray:
    selected = canonical_classification_preprocessing(mode)
    pixels = np.asarray(rgb_uint8)
    if pixels.dtype != np.uint8 or pixels.ndim != 3 or pixels.shape[2] != 3 or not pixels.flags.c_contiguous:
        raise ValueError("physical image must be contiguous uint8 HWC RGB")
    value = np.asarray(pixels, dtype=np.float32) / np.float32(255.0)
    if selected == CLASSIFICATION_PREPROCESSING_IMAGENET:
        mean = np.asarray(IMAGENET_RGB_MEAN, dtype=np.float32).reshape(1, 1, 3)
        std = np.asarray(IMAGENET_RGB_STD, dtype=np.float32).reshape(1, 1, 3)
        value = (value - mean) / std
    layout_token = str(layout).strip().upper()
    if layout_token == "NCHW":
        value = np.transpose(value, (2, 0, 1))
    elif layout_token != "NHWC":
        raise ValueError(f"unsupported image layout: {layout}")
    return np.ascontiguousarray(value[None, ...], dtype=np.float32)


def select_classification_logits(
    outputs: Iterable[Any] | Mapping[str, Any], *, output_names: Sequence[str] | None = None,
    output_name: str | None = None, class_count: int | None = None,
) -> np.ndarray:
    """Resolve the bound output, rejecting shape, batch, class and finite conflicts."""
    if isinstance(outputs, Mapping):
        names = list(outputs); arrays = list(outputs.values())
    else:
        arrays = list(outputs); names = list(output_names or [])
    if names and (len(names) != len(arrays) or len(set(names)) != len(names)):
        raise ValueError("classification output names are not unique and complete")
    if output_name:
        if not names or output_name not in names:
            raise ValueError("bound classification output name missing")
        arrays = [arrays[names.index(output_name)]]
    candidates = []
    for raw in arrays:
        value = np.asarray(raw)
        shape = value.shape
        valid = (value.ndim == 1 or value.ndim == 2 and shape[0] == 1)
        if not valid or value.size < 5:
            if output_name: raise ValueError("bound classification output requires single sample class vector")
            continue
        if class_count is not None and value.size != class_count:
            raise ValueError("classification class count mismatch")
        if not np.issubdtype(value.dtype, np.floating):
            raise ValueError("classification integer output requires explicit dequantization contract")
        if not np.isfinite(value).all():
            raise ValueError("nonfinite classification output")
        candidates.append(np.asarray(value, dtype=np.float32).reshape(-1))
    if len(candidates) != 1:
        raise ValueError(f"classification probe requires exactly one unambiguous logits output; found {len(candidates)}")
    return np.ascontiguousarray(candidates[0], dtype=np.float32)


def topk(logits: np.ndarray, count: int = 5) -> list[int]:
    values = np.asarray(logits, dtype=np.float32).reshape(-1)
    if not np.isfinite(values).all():
        raise ValueError("nonfinite classification output")
    if values.size < count:
        raise ValueError(f"logits vector has fewer than {count} classes")
    # Stable ordering makes ties reproducible across runs.
    order = np.argsort(-values, kind="stable")[:count]
    return [int(index) for index in order]


def _cosine(left: np.ndarray, right: np.ndarray) -> float:
    a = np.asarray(left, dtype=np.float64).reshape(-1)
    b = np.asarray(right, dtype=np.float64).reshape(-1)
    denom = float(np.linalg.norm(a) * np.linalg.norm(b))
    return float(np.dot(a, b) / denom) if denom > 0 else 0.0


def run_paired_probe(
    *,
    model_path: str | Path,
    manifest_path: str | Path,
    expected_images: int = 500,
    verify_content: bool = False,
    providers: Sequence[str] = ("CPUExecutionProvider",),
    limit: int = 0, model_id: str = "", output_name: str | None = None,
    class_count: int | None = None, source_numeric_mode: str | None = None,
    raw_logits_path: str | Path | None = None,
) -> dict[str, Any]:
    """Run both preprocessing arms through one ONNX Runtime session."""

    model = Path(model_path).expanduser().resolve()
    if not model.is_file():
        raise FileNotFoundError(f"ONNX model not found: {model}")
    samples, dataset_identity = load_probe_samples(
        manifest_path,
        expected_count=expected_images,
        verify_content=verify_content, limit=limit,
    )
    try:
        import onnxruntime as ort  # type: ignore
        from PIL import Image
    except Exception as exc:  # pragma: no cover - explicit runtime dependency
        raise RuntimeError("onnxruntime and Pillow are required for this probe") from exc

    session_options = ort.SessionOptions()
    session_options.intra_op_num_threads = 1
    session_options.inter_op_num_threads = 1
    session = ort.InferenceSession(
        str(model), sess_options=session_options, providers=list(providers),
    )
    if list(session.get_providers()) != ["CPUExecutionProvider"]:
        raise ValueError("paired control requires actual CPUExecutionProvider only")
    outputs_meta = list(session.get_outputs())
    names = [str(o.name) for o in outputs_meta]
    if output_name is None and len(names) == 1: output_name = names[0]
    inputs = list(session.get_inputs())
    if len(inputs) != 1:
        raise ValueError(f"classification probe requires exactly one model input, got {len(inputs)}")
    model_input = inputs[0]
    if str(getattr(model_input, "type", "")) not in {"tensor(float)", "tensor(float32)"}:
        raise ValueError(f"classification probe requires float32 model input, got {model_input.type}")
    layout, target_hw = resolve_image_input_contract(model_input.shape)
    spatial_contract = canonical_image_preprocessing_contract("classification", target_hw)

    modes = (
        CLASSIFICATION_PREPROCESSING_CURRENT,
        CLASSIFICATION_PREPROCESSING_IMAGENET,
    )
    counts = {
        mode: {"top1_correct": 0, "top5_correct": 0}
        for mode in modes
    }
    paired = {
        "same_top1_prediction": 0,
        "changed_top1_prediction": 0,
        "corrected_by_imagenet_mean_std": 0,
        "regressed_by_imagenet_mean_std": 0,
        "both_top1_correct": 0,
        "both_top1_wrong": 0,
        "logit_cosine_sum": 0.0,
    }
    records: list[dict[str, Any]] = []
    saved_logits = {}
    for sample in samples:
        with Image.open(sample.path) as image:
            rgb = np.asarray(image.convert("RGB"))
        prepared, _geometry = prepare_rgb_uint8_image(rgb, spatial_contract)
        mode_results: dict[str, dict[str, Any]] = {}
        raw_logits: dict[str, np.ndarray] = {}
        # Observe the normal Native/CPU preparation function, then submit its
        # actual feed to the same CPU session as the diagnostic arms.
        from ..runners.native_full_input import _prepare_tensor
        normal_mode = source_numeric_mode or CLASSIFICATION_PREPROCESSING_IMAGENET
        normal_feed, _, _ = _prepare_tensor(sample.path, shape=model_input.shape,
            dtype=np.dtype('float32'), layout=layout, task='classification',
            normalization='scale_0_1' if normal_mode in {'scale_only', CLASSIFICATION_PREPROCESSING_CURRENT} else 'imagenet_mean_std',
            preprocess_mode='resize', pad_value=0)
        normal_outputs = session.run(None, {str(model_input.name): normal_feed})
        normal_logits = select_classification_logits(normal_outputs, output_names=names,
            output_name=output_name, class_count=class_count)
        saved_logits[f"sample_{len(records):03d}_production_reference"] = normal_logits.copy()
        for mode in modes:
            tensor = classification_input_tensor(prepared, mode=mode, layout=layout)
            outputs = session.run(None, {str(model_input.name): tensor})
            logits = select_classification_logits(outputs, output_names=names, output_name=output_name, class_count=class_count)
            if sample.label_id >= logits.size: raise ValueError("label outside documented class range")
            saved_logits[f"sample_{len(records):03d}_{mode}"] = logits.copy()
            prediction = topk(logits, 5)
            top1_hit = prediction[0] == sample.label_id
            top5_hit = sample.label_id in prediction
            counts[mode]["top1_correct"] += int(top1_hit)
            counts[mode]["top5_correct"] += int(top5_hit)
            raw_logits[mode] = logits
            mode_results[mode] = {
                "top1": prediction[0],
                "top1_top2_margin": float(logits[prediction[0]] - logits[prediction[1]]),
                "top5": prediction,
                "top1_hit": bool(top1_hit),
                "top5_hit": bool(top5_hit),
                "logits_sha256": hashlib.sha256(logits.tobytes(order="C")).hexdigest(),
            }

        current = mode_results[CLASSIFICATION_PREPROCESSING_CURRENT]
        corrected = mode_results[CLASSIFICATION_PREPROCESSING_IMAGENET]
        same_prediction = current["top1"] == corrected["top1"]
        paired["same_top1_prediction"] += int(same_prediction)
        paired["changed_top1_prediction"] += int(not same_prediction)
        paired["corrected_by_imagenet_mean_std"] += int(
            not current["top1_hit"] and corrected["top1_hit"]
        )
        paired["regressed_by_imagenet_mean_std"] += int(
            current["top1_hit"] and not corrected["top1_hit"]
        )
        paired["both_top1_correct"] += int(current["top1_hit"] and corrected["top1_hit"])
        paired["both_top1_wrong"] += int(not current["top1_hit"] and not corrected["top1_hit"])
        cosine = _cosine(
            raw_logits[CLASSIFICATION_PREPROCESSING_CURRENT],
            raw_logits[CLASSIFICATION_PREPROCESSING_IMAGENET],
        )
        paired["logit_cosine_sum"] += cosine
        records.append({
            "image_id": sample.image_id,
            "label_id": sample.label_id,
            "modes": mode_results,
            "paired_logit_cosine": cosine,
            "production_reference": {"feed_sha256":hashlib.sha256(normal_feed.tobytes()).hexdigest(),
                "top5":topk(normal_logits),"normalization":normal_mode,
                "source_semantics_resolved":source_numeric_mode is not None,
                "producer":"native_full_input._prepare_tensor -> actual CPU session.run"},
        })

    total = len(samples)
    metrics: dict[str, Any] = {}
    for mode in modes:
        top1_correct = int(counts[mode]["top1_correct"])
        top5_correct = int(counts[mode]["top5_correct"])
        metrics[mode] = {
            **counts[mode],
            "sample_count": total,
            "top1": top1_correct / float(total),
            "top5": top5_correct / float(total),
            "preprocessing_contract": deepx_classification_preprocessing_contract(mode),
        }
    paired_summary = {
        key: value for key, value in paired.items() if key != "logit_cosine_sum"
    }
    paired_summary["mean_logit_cosine"] = paired["logit_cosine_sum"] / float(total)
    paired_summary["top1_delta_imagenet_minus_scale_only"] = (
        metrics[CLASSIFICATION_PREPROCESSING_IMAGENET]["top1"]
        - metrics[CLASSIFICATION_PREPROCESSING_CURRENT]["top1"]
    )
    paired_summary["top5_delta_imagenet_minus_scale_only"] = (
        metrics[CLASSIFICATION_PREPROCESSING_IMAGENET]["top5"]
        - metrics[CLASSIFICATION_PREPROCESSING_CURRENT]["top5"]
    )

    if raw_logits_path is not None:
        if sum(v.nbytes for v in saved_logits.values()) > 128 * 1024 * 1024:
            raise ValueError("probe raw logits byte budget exceeded")
        raw_path = Path(raw_logits_path)
        if raw_path.exists(): raise ValueError("diagnostic output already exists")
        raw_path.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(raw_path, **saved_logits)
    return {
        "schema": PROBE_SCHEMA,
        "schema_version": PROBE_SCHEMA_VERSION,
        "diagnostic_only": True, "counts_as_benchmark": False, "hardware_executed": False,
        "model_acceptance": "NOT_EVALUATED", "source_numeric_mode": source_numeric_mode or "unresolved",
        "arm_labels": {CLASSIFICATION_PREPROCESSING_CURRENT: "scale_only", CLASSIFICATION_PREPROCESSING_IMAGENET: "mean_std"},
        "model": {
            "model_id": model_id, "output_name": output_name,
            "path": str(model),
            "sha256": sha256_file(model),
            "bytes": model.stat().st_size,
            "input_name": str(model_input.name),
            "input_shape": list(model_input.shape),
            "input_layout": layout,
        },
        "dataset": dataset_identity,
        "spatial_preprocessing_contract": spatial_contract,
        "spatial_preprocessing_contract_sha256": preprocessing_contract_sha256(spatial_contract),
        "providers_requested": list(providers),
        "providers_effective": list(session.get_providers()),
        "modes": metrics,
        "paired": paired_summary,
        "records": records,
        "records_sha256": canonical_json_sha256(records),
        "interpretation": {
            "scope": "float_onnx_preprocessing_control_only",
            "quantization_emulated": False,
            "compiler_effects_measured": False,
            "decision_rule": (
                "A large scale-only loss recovered by imagenet_mean_std supports a "
                "preprocessing-domain cause. Residual hardware loss after the matched "
                "DXNN A/B remains a compiled-model/runtime difference with unresolved subcause."
            ),
        },
    }



def resolve_source_build_semantics(*, model_id: str, graph_observation: Mapping[str, Any],
                                   output_contract: Mapping[str, Any], profile_mode: str,
                                   export_metadata: Mapping[str, Any] | None = None) -> dict[str, Any]:
    """Diagnose declared source numerics without guessing fused/vendor operations.

    Graph observation is produced by the existing bounded ONNX inspector. Its
    constants and dataflow, not node names or validation accuracy, are authority.
    """
    if output_contract.get('model_id') != model_id:
        raise ValueError('model_input_identity_mismatch')
    for key in ('source_onnx_sha256', 'build_onnx_sha256', 'artifact_sha256'):
        value = str(output_contract.get(key) or '').removeprefix('sha256:')
        if len(value) != 64 or any(c not in '0123456789abcdef' for c in value):
            raise ValueError('model_input_identity_missing:' + key)
    metadata = dict(graph_observation.get('metadata') or {})
    export = dict((export_metadata or {}).get('preprocess') or {})
    def vector(name):
        value = metadata.get(name, export.get(name))
        if isinstance(value, str):
            try: value = json.loads(value)
            except ValueError: return None
        if not isinstance(value, list) or len(value) != 3: return None
        result = np.asarray(value, dtype=np.float32)
        return result if np.isfinite(result).all() else None
    mean, std = vector('mean'), vector('std')
    nodes = list(graph_observation.get('input_dataflow') or [])
    first = [n for n in nodes if n.get('depth') == 0]
    embedded = False
    evidence = 'unresolved'
    if mean is not None and std is not None and np.all(std > 0) and len(first) == 1:
        if first[0].get('op_type') == 'Conv' and metadata.get('source') == 'torchvision':
            evidence = 'declared_source_metadata_and_observed_input_conv'
        elif first[0].get('op_type') == 'Sub':
            subtract = first[0]
            children = [n for n in nodes if n.get('op_type') == 'Div' and any(x in subtract.get('outputs',[]) for x in n.get('inputs',[]))]
            means = list((subtract.get('small_initializer_values') or {}).values())
            deviations = list((children[0].get('small_initializer_values') or {}).values()) if len(children)==1 else []
            embedded = any(np.asarray(v,dtype=np.float32).size==3 and np.array_equal(np.asarray(v,dtype=np.float32).reshape(3),mean) for v in means) and any(np.asarray(v,dtype=np.float32).size==3 and np.array_equal(np.asarray(v,dtype=np.float32).reshape(3),std) for v in deviations)
            if embedded: evidence = 'observed_sub_div_constants_match_declared_mean_std'
    source_mode = 'scale_only' if embedded else ('imagenet_mean_std' if evidence != 'unresolved' else 'unresolved')
    mode = str(output_contract.get('classification_preprocessing') or '')
    reasons = []
    if evidence == 'unresolved': reasons.append('model_input_semantics_unresolved')
    if mode != profile_mode: reasons.append('classification_profile_receipt_mode_mismatch')
    if source_mode == 'imagenet_mean_std' and mode == CLASSIFICATION_PREPROCESSING_CURRENT:
        reasons.append('deepx_legacy_classification_preprocessing')
    if embedded and mode == CLASSIFICATION_PREPROCESSING_IMAGENET:
        reasons.append('duplicate_graph_normalization')
    if mode == CLASSIFICATION_PREPROCESSING_IMAGENET and output_contract['source_onnx_sha256'] == output_contract['build_onnx_sha256']:
        reasons.append('mean_std_adapter_build_identity_missing')
    return {'model_id':model_id,'status':'mismatch' if reasons else 'consistent_declared_chain',
            'source_numeric_mode':source_mode,'source_evidence':evidence,'source_graph_embedded_normalization':embedded,
            'build_classification_mode':mode,'profile_classification_mode':profile_mode,
            'spatial_contract':output_contract.get('preprocessing_contract'),
            'spatial_hash_is_numeric_proof':False,'mean':mean.tolist() if mean is not None else None,
            'std':std.tolist() if std is not None else None,'reasons':reasons,
            'logical_input_status':'reconstructed','vendor_internal_input_status':'unresolved',
            'hardware_executed':False,'counts_as_benchmark':False}


def compare_logical_input(physical_rgb: np.ndarray, observed_float: np.ndarray, *, mode: str,
                          layout: str = 'NCHW') -> dict[str, Any]:
    expected = classification_input_tensor(physical_rgb, mode=mode, layout=layout)
    actual = np.asarray(observed_float)
    if actual.dtype != np.float32 or actual.shape != expected.shape or not actual.flags.c_contiguous:
        raise ValueError('logical_input_dtype_shape_strides_mismatch')
    if not np.isfinite(actual).all(): raise ValueError('logical_input_nonfinite')
    delta=np.abs(actual.astype(np.float64)-expected.astype(np.float64))
    positions=np.argwhere(delta>1e-6)
    return {'consistent':bool(np.allclose(actual,expected,rtol=0,atol=1e-6)),
            'max_abs':float(delta.max()),'changed_elements':int(np.count_nonzero(delta)),
            'mismatch_positions':positions[:8].tolist(),'expected_status':'reconstructed',
            'observed_status':'observed_at_call','mapping':mode}


def compare_prediction_errors(full: Sequence[Mapping[str,Any]], split: Sequence[Mapping[str,Any]] | None) -> dict[str,Any]:
    """Compare identities, predictions and error sets, never infer cause from rates."""
    if split is None:return {'status':'split_control_missing','full_available':True,'common_cause_proven':False}
    left={str(r['image_id']):r for r in full};right={str(r['image_id']):r for r in split}
    if len(left)!=len(full) or len(right)!=len(split) or set(left)!=set(right):raise ValueError('full_split_sample_identity_mismatch')
    if any(left[k]['label_id']!=right[k]['label_id'] for k in left):raise ValueError('full_split_label_mismatch')
    lf={k for k,v in left.items() if v['top1']!=v['label_id']};rf={k for k,v in right.items() if v['top1']!=v['label_id']}
    return {'status':'compared','full_error_ids':sorted(lf),'split_error_ids':sorted(rf),
            'shared_error_ids':sorted(lf&rf),'same_error_images':lf==rf,
            'prediction_agreement_count':sum(left[k]['top1']==right[k]['top1'] for k in left),
            'common_cause_proven':False}
