#!/usr/bin/env python3
from __future__ import annotations

"""Create the v2.75.28 exact-identity YOLOv7-paper Final canary."""

import argparse
import importlib.util
from pathlib import Path
import sys
from types import ModuleType
from typing import Any, Mapping

import yaml


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from onnx_splitpoint_tool.benchmark.evaluation_profiles import (
    validate_evaluation_profile_payload,
)
from onnx_splitpoint_tool.campaign import build_campaign_readiness, readiness_markdown
from onnx_splitpoint_tool.workflow.artifacts import write_json, write_text


LEGACY_GENERATOR = ROOT / "scripts/create_v27527_yolov7_final_canary_profile.py"
DEFAULT_PROFILE_ID = "yolov7_paper_final_contract_canary_v27528"


def _load_legacy_generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "v27527_exact_yolov7_paper_canary_generator", LEGACY_GENERATOR
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load audited canary generator: {LEGACY_GENERATOR}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_LEGACY = _load_legacy_generator()


def _load(path: Path) -> dict[str, Any]:
    return _LEGACY._load(path)


def _yolov7_rows(profile: Mapping[str, Any]) -> list[dict[str, Any]]:
    return _LEGACY._yolov7_rows(profile)


def build_canary(source: Mapping[str, Any], *, profile_id: str) -> dict[str, Any]:
    profile = _LEGACY.build_canary(source, profile_id=profile_id)
    profile["implementation_note"] = (
        "Generated by create_v27528_yolov7_final_canary_profile.py from the "
        "single exact model id yolov7_paper. Preflight must be final_ready "
        "before hardware dispatch. Energy runs serially. A passing canary is "
        "necessary but does not itself authorize Final."
    )
    return validate_evaluation_profile_payload(profile)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-profile", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--preflight-dir", default="")
    parser.add_argument("--profile-id", default="")
    args = parser.parse_args()

    source_path = Path(args.source_profile).expanduser().resolve(strict=True)
    destination = Path(args.out).expanduser().resolve()
    profile_id = str(args.profile_id or "").strip() or DEFAULT_PROFILE_ID
    profile = build_canary(_load(source_path), profile_id=profile_id)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        yaml.safe_dump(profile, sort_keys=False, allow_unicode=True),
        encoding="utf-8",
    )
    report = build_campaign_readiness(profile, profile_path=destination)
    preflight_dir = (
        Path(args.preflight_dir).expanduser().resolve()
        if args.preflight_dir
        else destination.with_suffix("").with_name(destination.stem + "_preflight")
    )
    preflight_dir.mkdir(parents=True, exist_ok=True)
    write_json(preflight_dir / "campaign_readiness.json", report)
    write_text(preflight_dir / "campaign_readiness.md", readiness_markdown(report))
    print(f"PROFILE={destination}")
    print(f"PREFLIGHT={preflight_dir}")
    print(f"CLAIM_SCOPE={report.get('claim_scope')}")
    print(f"STATUS={report.get('status')}")
    print(f"REQUIRED_FAILURES={report.get('required_failure_count')}")
    return 0 if report.get("final_ready") else 2


if __name__ == "__main__":
    raise SystemExit(main())
